import { Inter } from 'next/font/google'
import '../../public/assets/css/style.scss'
import '../../public/assets/css/bootstrap.css'
import '../../public/assets/css/responsive.css'
import '../../public/assets/css/bootstrap.css'
import Header from './(components)/(Common)/Header'
import Footer from './(components)/(Common)/Footer'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
